apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metadata-dev
  namespace: fluxcd
spec:
  interval: 1m
  releaseName: metadata-dev
  chart:
    spec:
      chart: metadata
      sourceRef:
        kind: GitRepository
        name: metadata-helm-charts 
  values:
    appName: metadata
    namespace: development
    replicaCount: 1
    image:
      repository: igrubio/metadata
      pullPolicy: IfNotPresent
      tag: "2022"
    ingress:
      host: "dev.metadata.local"
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
